# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 476111b3fae44bc13ba42dc0313d1825305109f03bc4fd70081afa69fb576d2437e3117c5244055ea6bcf4f5feffe881c061cc6938aba8b016cb8f263e1755d7

test:
  secret_key_base: cdc874f19df6b2ce25f019426ddaa5f315d14eed44199ebc999f461e43664bdffe1515ad97288cb36d01e1d150500eb3df2ec5cc3f83911ad1d043396b58adb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
